// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/teko.proto

package teko_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCinemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCinemaRequest) Reset()         { *m = GetCinemaRequest{} }
func (m *GetCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*GetCinemaRequest) ProtoMessage()    {}
func (*GetCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{0}
}

func (m *GetCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCinemaRequest.Unmarshal(m, b)
}
func (m *GetCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCinemaRequest.Marshal(b, m, deterministic)
}
func (m *GetCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCinemaRequest.Merge(m, src)
}
func (m *GetCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_GetCinemaRequest.Size(m)
}
func (m *GetCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCinemaRequest proto.InternalMessageInfo

type CreateCinemaRequest struct {
	Cinema               *Cinema  `protobuf:"bytes,1,opt,name=cinema,proto3" json:"cinema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaRequest) Reset()         { *m = CreateCinemaRequest{} }
func (m *CreateCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaRequest) ProtoMessage()    {}
func (*CreateCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{1}
}

func (m *CreateCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaRequest.Unmarshal(m, b)
}
func (m *CreateCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaRequest.Marshal(b, m, deterministic)
}
func (m *CreateCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaRequest.Merge(m, src)
}
func (m *CreateCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaRequest.Size(m)
}
func (m *CreateCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaRequest proto.InternalMessageInfo

func (m *CreateCinemaRequest) GetCinema() *Cinema {
	if m != nil {
		return m.Cinema
	}
	return nil
}

type ConfigureCinemaSizeRequest struct {
	NewNumberOfColumns   int32    `protobuf:"varint,1,opt,name=newNumberOfColumns,proto3" json:"newNumberOfColumns,omitempty"`
	NewNumberOfRows      int32    `protobuf:"varint,2,opt,name=newNumberOfRows,proto3" json:"newNumberOfRows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureCinemaSizeRequest) Reset()         { *m = ConfigureCinemaSizeRequest{} }
func (m *ConfigureCinemaSizeRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureCinemaSizeRequest) ProtoMessage()    {}
func (*ConfigureCinemaSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{2}
}

func (m *ConfigureCinemaSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureCinemaSizeRequest.Unmarshal(m, b)
}
func (m *ConfigureCinemaSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureCinemaSizeRequest.Marshal(b, m, deterministic)
}
func (m *ConfigureCinemaSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureCinemaSizeRequest.Merge(m, src)
}
func (m *ConfigureCinemaSizeRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureCinemaSizeRequest.Size(m)
}
func (m *ConfigureCinemaSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureCinemaSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureCinemaSizeRequest proto.InternalMessageInfo

func (m *ConfigureCinemaSizeRequest) GetNewNumberOfColumns() int32 {
	if m != nil {
		return m.NewNumberOfColumns
	}
	return 0
}

func (m *ConfigureCinemaSizeRequest) GetNewNumberOfRows() int32 {
	if m != nil {
		return m.NewNumberOfRows
	}
	return 0
}

type ChangeMinimumDistanceRequest struct {
	MinimumDistance      int32    `protobuf:"varint,1,opt,name=minimumDistance,proto3" json:"minimumDistance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeMinimumDistanceRequest) Reset()         { *m = ChangeMinimumDistanceRequest{} }
func (m *ChangeMinimumDistanceRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeMinimumDistanceRequest) ProtoMessage()    {}
func (*ChangeMinimumDistanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{3}
}

func (m *ChangeMinimumDistanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeMinimumDistanceRequest.Unmarshal(m, b)
}
func (m *ChangeMinimumDistanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeMinimumDistanceRequest.Marshal(b, m, deterministic)
}
func (m *ChangeMinimumDistanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeMinimumDistanceRequest.Merge(m, src)
}
func (m *ChangeMinimumDistanceRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeMinimumDistanceRequest.Size(m)
}
func (m *ChangeMinimumDistanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeMinimumDistanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeMinimumDistanceRequest proto.InternalMessageInfo

func (m *ChangeMinimumDistanceRequest) GetMinimumDistance() int32 {
	if m != nil {
		return m.MinimumDistance
	}
	return 0
}

type ReserveSeatsRequest struct {
	Seats                []*Seat  `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveSeatsRequest) Reset()         { *m = ReserveSeatsRequest{} }
func (m *ReserveSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*ReserveSeatsRequest) ProtoMessage()    {}
func (*ReserveSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{4}
}

func (m *ReserveSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveSeatsRequest.Unmarshal(m, b)
}
func (m *ReserveSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveSeatsRequest.Marshal(b, m, deterministic)
}
func (m *ReserveSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveSeatsRequest.Merge(m, src)
}
func (m *ReserveSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_ReserveSeatsRequest.Size(m)
}
func (m *ReserveSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveSeatsRequest proto.InternalMessageInfo

func (m *ReserveSeatsRequest) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

type FindAvailableSeatsRequest struct {
	NumberOfSeats        int32    `protobuf:"varint,2,opt,name=numberOfSeats,proto3" json:"numberOfSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAvailableSeatsRequest) Reset()         { *m = FindAvailableSeatsRequest{} }
func (m *FindAvailableSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAvailableSeatsRequest) ProtoMessage()    {}
func (*FindAvailableSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{5}
}

func (m *FindAvailableSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAvailableSeatsRequest.Unmarshal(m, b)
}
func (m *FindAvailableSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAvailableSeatsRequest.Marshal(b, m, deterministic)
}
func (m *FindAvailableSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAvailableSeatsRequest.Merge(m, src)
}
func (m *FindAvailableSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAvailableSeatsRequest.Size(m)
}
func (m *FindAvailableSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAvailableSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAvailableSeatsRequest proto.InternalMessageInfo

func (m *FindAvailableSeatsRequest) GetNumberOfSeats() int32 {
	if m != nil {
		return m.NumberOfSeats
	}
	return 0
}

type GetCinemaResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Cinema               *Cinema  `protobuf:"bytes,2,opt,name=Cinema,proto3" json:"Cinema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCinemaResponse) Reset()         { *m = GetCinemaResponse{} }
func (m *GetCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*GetCinemaResponse) ProtoMessage()    {}
func (*GetCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{6}
}

func (m *GetCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCinemaResponse.Unmarshal(m, b)
}
func (m *GetCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCinemaResponse.Marshal(b, m, deterministic)
}
func (m *GetCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCinemaResponse.Merge(m, src)
}
func (m *GetCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_GetCinemaResponse.Size(m)
}
func (m *GetCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCinemaResponse proto.InternalMessageInfo

func (m *GetCinemaResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetCinemaResponse) GetCinema() *Cinema {
	if m != nil {
		return m.Cinema
	}
	return nil
}

type CreateCinemaResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NewCinema            *Cinema  `protobuf:"bytes,2,opt,name=newCinema,proto3" json:"newCinema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCinemaResponse) Reset()         { *m = CreateCinemaResponse{} }
func (m *CreateCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCinemaResponse) ProtoMessage()    {}
func (*CreateCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{7}
}

func (m *CreateCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCinemaResponse.Unmarshal(m, b)
}
func (m *CreateCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCinemaResponse.Marshal(b, m, deterministic)
}
func (m *CreateCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCinemaResponse.Merge(m, src)
}
func (m *CreateCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCinemaResponse.Size(m)
}
func (m *CreateCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCinemaResponse proto.InternalMessageInfo

func (m *CreateCinemaResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateCinemaResponse) GetNewCinema() *Cinema {
	if m != nil {
		return m.NewCinema
	}
	return nil
}

type ConfigureCinemaSizeResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedCinema        *Cinema  `protobuf:"bytes,2,opt,name=updatedCinema,proto3" json:"updatedCinema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureCinemaSizeResponse) Reset()         { *m = ConfigureCinemaSizeResponse{} }
func (m *ConfigureCinemaSizeResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigureCinemaSizeResponse) ProtoMessage()    {}
func (*ConfigureCinemaSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{8}
}

func (m *ConfigureCinemaSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureCinemaSizeResponse.Unmarshal(m, b)
}
func (m *ConfigureCinemaSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureCinemaSizeResponse.Marshal(b, m, deterministic)
}
func (m *ConfigureCinemaSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureCinemaSizeResponse.Merge(m, src)
}
func (m *ConfigureCinemaSizeResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigureCinemaSizeResponse.Size(m)
}
func (m *ConfigureCinemaSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureCinemaSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureCinemaSizeResponse proto.InternalMessageInfo

func (m *ConfigureCinemaSizeResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ConfigureCinemaSizeResponse) GetUpdatedCinema() *Cinema {
	if m != nil {
		return m.UpdatedCinema
	}
	return nil
}

type ChangeMinimumDistanceResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedCinema        *Cinema  `protobuf:"bytes,2,opt,name=updatedCinema,proto3" json:"updatedCinema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeMinimumDistanceResponse) Reset()         { *m = ChangeMinimumDistanceResponse{} }
func (m *ChangeMinimumDistanceResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeMinimumDistanceResponse) ProtoMessage()    {}
func (*ChangeMinimumDistanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{9}
}

func (m *ChangeMinimumDistanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeMinimumDistanceResponse.Unmarshal(m, b)
}
func (m *ChangeMinimumDistanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeMinimumDistanceResponse.Marshal(b, m, deterministic)
}
func (m *ChangeMinimumDistanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeMinimumDistanceResponse.Merge(m, src)
}
func (m *ChangeMinimumDistanceResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeMinimumDistanceResponse.Size(m)
}
func (m *ChangeMinimumDistanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeMinimumDistanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeMinimumDistanceResponse proto.InternalMessageInfo

func (m *ChangeMinimumDistanceResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ChangeMinimumDistanceResponse) GetUpdatedCinema() *Cinema {
	if m != nil {
		return m.UpdatedCinema
	}
	return nil
}

type ReserveSeatsResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveSeatsResponse) Reset()         { *m = ReserveSeatsResponse{} }
func (m *ReserveSeatsResponse) String() string { return proto.CompactTextString(m) }
func (*ReserveSeatsResponse) ProtoMessage()    {}
func (*ReserveSeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{10}
}

func (m *ReserveSeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveSeatsResponse.Unmarshal(m, b)
}
func (m *ReserveSeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveSeatsResponse.Marshal(b, m, deterministic)
}
func (m *ReserveSeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveSeatsResponse.Merge(m, src)
}
func (m *ReserveSeatsResponse) XXX_Size() int {
	return xxx_messageInfo_ReserveSeatsResponse.Size(m)
}
func (m *ReserveSeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveSeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveSeatsResponse proto.InternalMessageInfo

func (m *ReserveSeatsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type FindAvailableSeatsResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAvailableSeatsResponse) Reset()         { *m = FindAvailableSeatsResponse{} }
func (m *FindAvailableSeatsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAvailableSeatsResponse) ProtoMessage()    {}
func (*FindAvailableSeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{11}
}

func (m *FindAvailableSeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAvailableSeatsResponse.Unmarshal(m, b)
}
func (m *FindAvailableSeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAvailableSeatsResponse.Marshal(b, m, deterministic)
}
func (m *FindAvailableSeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAvailableSeatsResponse.Merge(m, src)
}
func (m *FindAvailableSeatsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAvailableSeatsResponse.Size(m)
}
func (m *FindAvailableSeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAvailableSeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAvailableSeatsResponse proto.InternalMessageInfo

func (m *FindAvailableSeatsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *FindAvailableSeatsResponse) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{12}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Cinema struct {
	MinimumDistance      int32    `protobuf:"varint,1,opt,name=minimumDistance,proto3" json:"minimumDistance,omitempty"`
	NumberOfRows         int32    `protobuf:"varint,2,opt,name=numberOfRows,proto3" json:"numberOfRows,omitempty"`
	NumberOfColumns      int32    `protobuf:"varint,3,opt,name=numberOfColumns,proto3" json:"numberOfColumns,omitempty"`
	ReservedSeats        []*Seat  `protobuf:"bytes,4,rep,name=reservedSeats,proto3" json:"reservedSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cinema) Reset()         { *m = Cinema{} }
func (m *Cinema) String() string { return proto.CompactTextString(m) }
func (*Cinema) ProtoMessage()    {}
func (*Cinema) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{13}
}

func (m *Cinema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cinema.Unmarshal(m, b)
}
func (m *Cinema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cinema.Marshal(b, m, deterministic)
}
func (m *Cinema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cinema.Merge(m, src)
}
func (m *Cinema) XXX_Size() int {
	return xxx_messageInfo_Cinema.Size(m)
}
func (m *Cinema) XXX_DiscardUnknown() {
	xxx_messageInfo_Cinema.DiscardUnknown(m)
}

var xxx_messageInfo_Cinema proto.InternalMessageInfo

func (m *Cinema) GetMinimumDistance() int32 {
	if m != nil {
		return m.MinimumDistance
	}
	return 0
}

func (m *Cinema) GetNumberOfRows() int32 {
	if m != nil {
		return m.NumberOfRows
	}
	return 0
}

func (m *Cinema) GetNumberOfColumns() int32 {
	if m != nil {
		return m.NumberOfColumns
	}
	return 0
}

func (m *Cinema) GetReservedSeats() []*Seat {
	if m != nil {
		return m.ReservedSeats
	}
	return nil
}

type Seat struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column               int32    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40bd35ed3ee5584, []int{14}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Seat) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCinemaRequest)(nil), "teko_service.GetCinemaRequest")
	proto.RegisterType((*CreateCinemaRequest)(nil), "teko_service.CreateCinemaRequest")
	proto.RegisterType((*ConfigureCinemaSizeRequest)(nil), "teko_service.ConfigureCinemaSizeRequest")
	proto.RegisterType((*ChangeMinimumDistanceRequest)(nil), "teko_service.ChangeMinimumDistanceRequest")
	proto.RegisterType((*ReserveSeatsRequest)(nil), "teko_service.ReserveSeatsRequest")
	proto.RegisterType((*FindAvailableSeatsRequest)(nil), "teko_service.FindAvailableSeatsRequest")
	proto.RegisterType((*GetCinemaResponse)(nil), "teko_service.GetCinemaResponse")
	proto.RegisterType((*CreateCinemaResponse)(nil), "teko_service.CreateCinemaResponse")
	proto.RegisterType((*ConfigureCinemaSizeResponse)(nil), "teko_service.ConfigureCinemaSizeResponse")
	proto.RegisterType((*ChangeMinimumDistanceResponse)(nil), "teko_service.ChangeMinimumDistanceResponse")
	proto.RegisterType((*ReserveSeatsResponse)(nil), "teko_service.ReserveSeatsResponse")
	proto.RegisterType((*FindAvailableSeatsResponse)(nil), "teko_service.FindAvailableSeatsResponse")
	proto.RegisterType((*Status)(nil), "teko_service.Status")
	proto.RegisterType((*Cinema)(nil), "teko_service.Cinema")
	proto.RegisterType((*Seat)(nil), "teko_service.Seat")
}

func init() {
	proto.RegisterFile("proto/teko.proto", fileDescriptor_c40bd35ed3ee5584)
}

var fileDescriptor_c40bd35ed3ee5584 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4b, 0x8f, 0xd3, 0x30,
	0x10, 0xa6, 0xdb, 0x6e, 0x51, 0xa7, 0xad, 0xb6, 0xb8, 0x05, 0x95, 0xf0, 0x5a, 0x2c, 0x24, 0xca,
	0x43, 0x05, 0x15, 0x09, 0x21, 0x2e, 0x68, 0x95, 0x15, 0x70, 0x61, 0x91, 0x52, 0x24, 0x8e, 0x28,
	0x6d, 0x67, 0x8b, 0xb5, 0x8d, 0x5d, 0x62, 0xa7, 0x45, 0x5c, 0x39, 0x20, 0xfe, 0x12, 0xbf, 0x0e,
	0xc5, 0x71, 0xb3, 0x75, 0x36, 0x59, 0xa2, 0x1e, 0x38, 0x65, 0x32, 0xfe, 0xfc, 0xcd, 0x67, 0xcf,
	0xc3, 0xd0, 0x59, 0x86, 0x42, 0x89, 0x67, 0x0a, 0xcf, 0xc4, 0x50, 0x9b, 0xa4, 0x15, 0xdb, 0x5f,
	0x24, 0x86, 0x2b, 0x36, 0x45, 0x4a, 0xa0, 0xf3, 0x0e, 0x95, 0xcb, 0x38, 0x06, 0xbe, 0x87, 0xdf,
	0x22, 0x94, 0x8a, 0xba, 0xd0, 0x75, 0x43, 0xf4, 0x15, 0x5a, 0x6e, 0xf2, 0x14, 0xea, 0x53, 0xed,
	0xe8, 0x57, 0x0e, 0x2b, 0x83, 0xe6, 0xa8, 0x37, 0xdc, 0x66, 0x1a, 0x1a, 0xb0, 0xc1, 0xd0, 0x15,
	0x38, 0xae, 0xe0, 0xa7, 0x6c, 0x1e, 0x85, 0x86, 0x67, 0xcc, 0x7e, 0xe0, 0x86, 0x6b, 0x08, 0x84,
	0xe3, 0xfa, 0x24, 0x0a, 0x26, 0x18, 0x7e, 0x3c, 0x75, 0xc5, 0x22, 0x0a, 0xb8, 0xd4, 0xbc, 0xfb,
	0x5e, 0xce, 0x0a, 0x19, 0xc0, 0xc1, 0x96, 0xd7, 0x13, 0x6b, 0xd9, 0xdf, 0xd3, 0xe0, 0xac, 0x9b,
	0xbe, 0x87, 0xdb, 0xee, 0x57, 0x9f, 0xcf, 0xf1, 0x03, 0xe3, 0x2c, 0x88, 0x82, 0x63, 0x26, 0x95,
	0xcf, 0xa7, 0x69, 0xe4, 0x01, 0x1c, 0x04, 0xf6, 0x8a, 0x09, 0x9b, 0x75, 0xd3, 0x37, 0xd0, 0xf5,
	0x30, 0x3e, 0x1d, 0x8e, 0xd1, 0x57, 0xf2, 0x9c, 0x60, 0x5f, 0xc6, 0xff, 0xfd, 0xbd, 0xc3, 0xea,
	0xa0, 0x39, 0x22, 0xf6, 0x2d, 0xc4, 0x50, 0x2f, 0x01, 0xd0, 0x23, 0xb8, 0xf9, 0x96, 0xf1, 0xd9,
	0xd1, 0xca, 0x67, 0x0b, 0x7f, 0xb2, 0xb0, 0x69, 0x1e, 0x40, 0x9b, 0x1b, 0xdd, 0x63, 0x43, 0x17,
	0xab, 0xb0, 0x9d, 0x54, 0xc0, 0xb5, 0xad, 0xf4, 0xc8, 0xa5, 0xe0, 0x12, 0xe3, 0x44, 0x48, 0xe5,
	0xab, 0x48, 0xe6, 0x27, 0x62, 0xac, 0xd7, 0x3c, 0x83, 0x89, 0xd1, 0xc9, 0x7e, 0x1d, 0xa1, 0x30,
	0x6d, 0xc9, 0x97, 0x7e, 0x87, 0x9e, 0x9d, 0xfb, 0x9d, 0x62, 0x8e, 0xa0, 0xc1, 0x71, 0x5d, 0x22,
	0xec, 0x39, 0x8c, 0xfe, 0xaa, 0xc0, 0xad, 0xdc, 0x8a, 0xd9, 0x49, 0xc1, 0x6b, 0x68, 0x47, 0xcb,
	0x99, 0xaf, 0x70, 0x56, 0x42, 0x85, 0x0d, 0xa5, 0xbf, 0x2b, 0x70, 0xa7, 0xa0, 0x86, 0xfe, 0xbb,
	0x96, 0x63, 0xe8, 0xd9, 0x45, 0xb8, 0x8b, 0x02, 0xaa, 0xc0, 0xc9, 0xab, 0xc4, 0x9d, 0x4e, 0x53,
	0xbe, 0xfe, 0x5f, 0x42, 0x3d, 0xd9, 0x4b, 0x08, 0xd4, 0xa6, 0x62, 0xb6, 0xe9, 0x34, 0x6d, 0x93,
	0x3e, 0x5c, 0x0d, 0x50, 0x4a, 0x7f, 0x8e, 0xfa, 0x3e, 0x1a, 0xde, 0xe6, 0x97, 0xfe, 0xa9, 0x6c,
	0x4a, 0xb6, 0x7c, 0xb7, 0x12, 0x0a, 0x2d, 0x7e, 0x71, 0x3c, 0x58, 0x3e, 0x3d, 0x45, 0x32, 0x23,
	0xa7, 0x6a, 0xa6, 0x48, 0x66, 0xde, 0xbc, 0x82, 0x76, 0x98, 0x5c, 0xfb, 0x2c, 0xe9, 0xce, 0x5a,
	0xe1, 0x61, 0x6d, 0x20, 0x7d, 0x0e, 0xb5, 0xd8, 0x20, 0x1d, 0xa8, 0x86, 0x62, 0x6d, 0xd4, 0xc6,
	0x26, 0xb9, 0x01, 0xf5, 0xa9, 0xa6, 0x37, 0xda, 0xcc, 0xdf, 0xe8, 0x67, 0x0d, 0x9a, 0x9f, 0xf0,
	0x4c, 0x8c, 0x13, 0x56, 0xc2, 0x80, 0x5c, 0x4c, 0x16, 0x79, 0x68, 0x87, 0x2e, 0x1c, 0x2c, 0xce,
	0xe0, 0xdf, 0xc0, 0x24, 0xef, 0xf4, 0x0a, 0xf9, 0x0c, 0xad, 0xed, 0xea, 0x22, 0xf7, 0xed, 0xbd,
	0x39, 0xe3, 0xcf, 0xa1, 0x97, 0x41, 0x52, 0xe2, 0x05, 0x74, 0x73, 0x7a, 0x99, 0x64, 0xb4, 0x15,
	0x3f, 0x10, 0xce, 0xa3, 0x12, 0xc8, 0x34, 0x5a, 0x08, 0xd7, 0x73, 0xfb, 0x95, 0x3c, 0xce, 0xb0,
	0x5c, 0xf2, 0x30, 0x38, 0x4f, 0x4a, 0x61, 0xd3, 0x98, 0x27, 0xd0, 0x48, 0x27, 0x33, 0xb9, 0x6b,
	0xef, 0xcd, 0xbe, 0xa8, 0xce, 0xbd, 0xc2, 0xf5, 0x0d, 0xdf, 0xa4, 0xae, 0x5f, 0xe7, 0x17, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x73, 0xa9, 0x11, 0x14, 0xb1, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TekoServiceClient is the client API for TekoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TekoServiceClient interface {
	FindAvailableSeats(ctx context.Context, in *FindAvailableSeatsRequest, opts ...grpc.CallOption) (*FindAvailableSeatsResponse, error)
	ReserveSeats(ctx context.Context, in *ReserveSeatsRequest, opts ...grpc.CallOption) (*ReserveSeatsResponse, error)
	ConfigureCinemaSize(ctx context.Context, in *ConfigureCinemaSizeRequest, opts ...grpc.CallOption) (*ConfigureCinemaSizeResponse, error)
	ChangeMinimumDistance(ctx context.Context, in *ChangeMinimumDistanceRequest, opts ...grpc.CallOption) (*ChangeMinimumDistanceResponse, error)
	GetCinema(ctx context.Context, in *GetCinemaRequest, opts ...grpc.CallOption) (*GetCinemaResponse, error)
}

type tekoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTekoServiceClient(cc grpc.ClientConnInterface) TekoServiceClient {
	return &tekoServiceClient{cc}
}

func (c *tekoServiceClient) FindAvailableSeats(ctx context.Context, in *FindAvailableSeatsRequest, opts ...grpc.CallOption) (*FindAvailableSeatsResponse, error) {
	out := new(FindAvailableSeatsResponse)
	err := c.cc.Invoke(ctx, "/teko_service.TekoService/FindAvailableSeats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tekoServiceClient) ReserveSeats(ctx context.Context, in *ReserveSeatsRequest, opts ...grpc.CallOption) (*ReserveSeatsResponse, error) {
	out := new(ReserveSeatsResponse)
	err := c.cc.Invoke(ctx, "/teko_service.TekoService/ReserveSeats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tekoServiceClient) ConfigureCinemaSize(ctx context.Context, in *ConfigureCinemaSizeRequest, opts ...grpc.CallOption) (*ConfigureCinemaSizeResponse, error) {
	out := new(ConfigureCinemaSizeResponse)
	err := c.cc.Invoke(ctx, "/teko_service.TekoService/ConfigureCinemaSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tekoServiceClient) ChangeMinimumDistance(ctx context.Context, in *ChangeMinimumDistanceRequest, opts ...grpc.CallOption) (*ChangeMinimumDistanceResponse, error) {
	out := new(ChangeMinimumDistanceResponse)
	err := c.cc.Invoke(ctx, "/teko_service.TekoService/ChangeMinimumDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tekoServiceClient) GetCinema(ctx context.Context, in *GetCinemaRequest, opts ...grpc.CallOption) (*GetCinemaResponse, error) {
	out := new(GetCinemaResponse)
	err := c.cc.Invoke(ctx, "/teko_service.TekoService/GetCinema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TekoServiceServer is the server API for TekoService service.
type TekoServiceServer interface {
	FindAvailableSeats(context.Context, *FindAvailableSeatsRequest) (*FindAvailableSeatsResponse, error)
	ReserveSeats(context.Context, *ReserveSeatsRequest) (*ReserveSeatsResponse, error)
	ConfigureCinemaSize(context.Context, *ConfigureCinemaSizeRequest) (*ConfigureCinemaSizeResponse, error)
	ChangeMinimumDistance(context.Context, *ChangeMinimumDistanceRequest) (*ChangeMinimumDistanceResponse, error)
	GetCinema(context.Context, *GetCinemaRequest) (*GetCinemaResponse, error)
}

// UnimplementedTekoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTekoServiceServer struct {
}

func (*UnimplementedTekoServiceServer) FindAvailableSeats(ctx context.Context, req *FindAvailableSeatsRequest) (*FindAvailableSeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAvailableSeats not implemented")
}
func (*UnimplementedTekoServiceServer) ReserveSeats(ctx context.Context, req *ReserveSeatsRequest) (*ReserveSeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveSeats not implemented")
}
func (*UnimplementedTekoServiceServer) ConfigureCinemaSize(ctx context.Context, req *ConfigureCinemaSizeRequest) (*ConfigureCinemaSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureCinemaSize not implemented")
}
func (*UnimplementedTekoServiceServer) ChangeMinimumDistance(ctx context.Context, req *ChangeMinimumDistanceRequest) (*ChangeMinimumDistanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMinimumDistance not implemented")
}
func (*UnimplementedTekoServiceServer) GetCinema(ctx context.Context, req *GetCinemaRequest) (*GetCinemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCinema not implemented")
}

func RegisterTekoServiceServer(s *grpc.Server, srv TekoServiceServer) {
	s.RegisterService(&_TekoService_serviceDesc, srv)
}

func _TekoService_FindAvailableSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAvailableSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TekoServiceServer).FindAvailableSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teko_service.TekoService/FindAvailableSeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TekoServiceServer).FindAvailableSeats(ctx, req.(*FindAvailableSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TekoService_ReserveSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TekoServiceServer).ReserveSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teko_service.TekoService/ReserveSeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TekoServiceServer).ReserveSeats(ctx, req.(*ReserveSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TekoService_ConfigureCinemaSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureCinemaSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TekoServiceServer).ConfigureCinemaSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teko_service.TekoService/ConfigureCinemaSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TekoServiceServer).ConfigureCinemaSize(ctx, req.(*ConfigureCinemaSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TekoService_ChangeMinimumDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMinimumDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TekoServiceServer).ChangeMinimumDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teko_service.TekoService/ChangeMinimumDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TekoServiceServer).ChangeMinimumDistance(ctx, req.(*ChangeMinimumDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TekoService_GetCinema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCinemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TekoServiceServer).GetCinema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teko_service.TekoService/GetCinema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TekoServiceServer).GetCinema(ctx, req.(*GetCinemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TekoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "teko_service.TekoService",
	HandlerType: (*TekoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAvailableSeats",
			Handler:    _TekoService_FindAvailableSeats_Handler,
		},
		{
			MethodName: "ReserveSeats",
			Handler:    _TekoService_ReserveSeats_Handler,
		},
		{
			MethodName: "ConfigureCinemaSize",
			Handler:    _TekoService_ConfigureCinemaSize_Handler,
		},
		{
			MethodName: "ChangeMinimumDistance",
			Handler:    _TekoService_ChangeMinimumDistance_Handler,
		},
		{
			MethodName: "GetCinema",
			Handler:    _TekoService_GetCinema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teko.proto",
}
